[package]
authors = ["Izzy Swart", "Tyler Poon"]
edition = "2018"
name = "vessels"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0.98", features = ["derive"] }
futures = "0.1.27"
crossbeam-channel = "0.3.9"

[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = "0.2.51"
itertools = "0.8.0"
web-sys = { version = "0.3.28", features = ["Document", "Window", "HtmlHeadElement", "Element", "HtmlElement", "Node", "EventTarget", "MouseEvent", "Event", "WheelEvent", "KeyboardEvent", "HtmlCanvasElement", "CanvasRenderingContext2d", "TextMetrics", "ImageData", "DomTokenList", "CanvasGradient", "CanvasPattern", "CssStyleDeclaration", "console"] }
js-sys = "0.3.28"

[target.asmjs-unknown-emscripten.dependencies]
wasm-bindgen = "0.2.51"
itertools = "0.8.0"
web-sys = { version = "0.3.28", features = ["Document", "Window", "HtmlHeadElement", "Element", "HtmlElement", "Node", "EventTarget", "MouseEvent", "Event", "WheelEvent", "KeyboardEvent", "HtmlCanvasElement", "CanvasRenderingContext2d", "TextMetrics", "ImageData", "DomTokenList", "CanvasGradient", "CanvasPattern", "CssStyleDeclaration", "console"] }
js-sys = "0.3.28"

[target.wasm32-unknown-emscripten.dependencies]
wasm-bindgen = "0.2.51"
itertools = "0.8.0"
web-sys = { version = "0.3.28", features = ["Document", "Window", "HtmlHeadElement", "Element", "HtmlElement", "Node", "EventTarget", "MouseEvent", "Event", "WheelEvent", "KeyboardEvent", "HtmlCanvasElement", "CanvasRenderingContext2d", "TextMetrics", "ImageData", "DomTokenList", "CanvasGradient", "CanvasPattern", "CssStyleDeclaration", "console"] }
js-sys = "0.3.28"

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
glutin = "0.20.0"
cairo-rs = "0.6.0"
tokio = "0.1.21"
gl = "0.11.0"
glib = "0.7.1"
lcms2 = "5.1.3"
libc = "0.2.54"
pangocairo = "0.7.0"
cairo-sys-rs = "0.8.0"
pango = "0.6.0"
itertools = "0.8.0"
lazy_static = "1.3.0"

[profile.release]
lto = true
debug = false
