[package]
name = "vessels_core"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
void = "1.0.2"
thiserror = "1.0.10"
anyhow = "1.0.26"
